# Basic site info
title:              "arwsoft. blog"
description:        "Tech blog for geeks"
keywords:           "arwsoft, personal blog, software engineer, life experience, technology and research"
logo_text:          "arwsoft."
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                http://blog.arwsoft.id # main url
baseurl:            null # for gh-pages
enforce_ssl:        blog.arwsoft.id
github_post_dir:    https://github.com/dannyarw/dannyarw.github.io/blob/master/

# Site author info
author:
  name:             "arwsoft"
  email:            danny@arwsoft.id
  github_username:  dannyarw
  twitter_username: dannyarw
  facebook_url:     https://www.facebook.com/danny.ariwicaksono

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   dabloggithub

# GA
google_analytics_code: UA-41801450-2

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Jakarta
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
